### ISSUE TITLE
Dark style needs text colors fixed

### ISSUE THREAD

**Issue by hyperknot** [hyperknot/openfreemap-styles#1]
Should be inverted from Positron using a nice color space

**Comment by hyperknot** [comment]
Dark Matter is the one I have forked. I can include those temporarily, they are just not polished like the other ones. But if you are OK with the unmodified Fjord or Dark Matter, then it's super simple to include them.

**Comment by dadofsambonzuki** [comment]
Yes, that works for now. We can perhaps create a bounty for a more polished Positron inversion.

We're seeing Fjord and Dark Matter make references to resources behind paywalls (e.g. MapTiler). Is that not an issue?

**Comment by hyperknot** [comment]
Those are either sprites (icons) or fonts. For fonts I recommend changing them to the Noto Sans ones in OFM.

Have a look at fix_styles.py, it's doing the search & replace for fonts and icons.
https://github.com/hyperknot/openfreemap-styles/blob/main/scripts/fix_styles.py

I think dark styles are generally quite minimalist, they don't use icons too much. 

But I'll have a look at adding those two styles as they are now, and then maybe making a new one in the future. If you create a bounty for a polished Positron inversion that sounds like a nice good idea!

**Comment by hyperknot** [comment]
I added the original Dark and Fiord styles, unmodified, but using Noto Sans.

Readme section:

Dark and Fiord is not yet complete. They are unmodified, which means they are exactly as they are on their source repo, with the only difference that fonts are set to Noto Sans.



To access Dark and Fiord, use these URLs (these are not offered on the Quick Start guide for the moment):

```
https://tiles.openfreemap.org/styles/dark
```

and

```
https://tiles.openfreemap.org/styles/fiord
```
