### ISSUE TITLE
streets-v2 and streets-v2-dark from maptiler

### ISSUE THREAD

**Issue by bugproof** [hyperknot/openfreemap-styles#5]
would it be possible to port it to work with openfreemap? probably my favourite map styles much better looking than bright/liberty and dark

If you can give me directions I'm willing to do it.

Unless there's copyright issue?

**Comment by bugproof** [comment]
[streets-v2-dark.json](https://github.com/user-attachments/files/17745471/streets-v2-dark.json)
[streets-v2.json](https://github.com/user-attachments/files/17745492/streets-v2.json)

**Comment by bugproof** [comment]
I will port them and add them as gist if anyone's interested :)

**Comment by klokan** [comment]
It is amazing to hear on this place about the great quality of the professional styles developed by cartographers working on the MapTiler platform (https://www.maptiler.com/), which offers everyone FREE plan for integrating these maps in websites, apps and other products.

MapTiler team generously created and publish and maintain together with community the *open-source styles* for OpenMapTiles project listed at https://openmaptiles.org/styles/ and published with open license in relevant linked GitHub repositories.

Only these styles can be used legally with self-hosted or self-generated OpenMapTiles, modified or unmodified, while following the required attribution and license present in the original GitHub repos. Start on our Github and nowhere else, please.

The MapTiler platform offers many significantly better and reworked professional styles, which are exclusive for MapTiler Platform. These are NOT ON GITHUB - and they can be used online with https://cloud.maptiler.com/ or with self-hosting via https://www.maptiler.com/server/. Usage outside the MapTiler platform is illegal without written permission. By properly downloading the style from our Customize tool in Cloud you receive the complete license. The JSONs above are copyright MapTiler and they should not be redistributed.

**Comment by hyperknot** [comment]
@klokan thanks for clarifying the licenses. The GitHub repo only has officially sourced styles, and I am very careful not to include anything without an open-source license. If you are referring to the comment by bugproof linking to the styles as "hosting", I've deleted it now.

**Comment by bugproof** [comment]
It would be nice to create more visually pleasing designs using open source visual editor maputnik for community to use.

**Comment by hyperknot** [comment]
@bugproof it takes a lot of work to create those visually pleasing designs. Feel free to contribute to this repo, or have a look at https://github.com/versatiles-org/versatiles-style, which we might migrate to one day in the future.

**Comment by luis-suter** [comment]
Quick shameless plug ;) clarifying that a 10k USD bill is unusual. Your volumes have to be quite big and MapTiler offers substantial volume discounts for high-volume users. 

We also give discounts for non-profit and actions like placing our logo on the map.

In case you're ever frustrated with a bill, just drop us a mail :)

**Comment by hyperknot** [comment]
I think the free tiers of different providers and discounts and private messages are totally irrelevant here. The aim with OpenFreeMap was to make a public + self-hostable solution which would never occur any costs, and does not depend on provider pricing discounts.
